// Shadcn/ui atomic components (base layer)
export * from './atoms'

// Composite components (molecules/organisms) - backward compatible API
export { Button } from './Button'
export { Badge } from './Badge'
export { Container } from './Container'
export { Section } from './Section'
export { HeroSection } from './HeroSection'
export { ProjectCard } from './ProjectCard'
export { ProjectModal } from './ProjectModal'
export { SearchInput } from './SearchInput'
export { Dropdown } from './Dropdown'
export { ControlsBar } from './ControlsBar'
export { PageHeader } from './PageHeader'
export { ResultsInfo } from './ResultsInfo'
export { ProjectGrid } from './ProjectGrid'
export { ValueCard } from './ValueCard'
export { SectionHeader } from './SectionHeader'
export { SkillCategoryCard } from './SkillCategoryCard'
export { TimelineItem } from './TimelineItem'
